kind: ReplicationController
apiVersion: v1
metadata:
  name: etcd-discovery
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    name: etcd-discovery
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: etcd-discovery
    spec:
      containers:
      - name: discovery
        image: openshift/etcd-20-centos7
        args:
        - etcd-discovery.sh
        ports:
        - containerPort: 2379
          protocol: TCP
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities: {}
          privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccount: ''
status:
  replicas: 1
